# Site settings
title: Smart Labs Doc
email: marcus@smartlabs.no
description: > 
  Jekyll Template for Project Websites
  providing documentation and blog post pages.

baseurl: "/docs-smartlabs" # the subpath of your site, e.g. /blog/
url: https://marcusrognes.github.io/docs-smartlabs/ # the base hostname & protocol for your site
git_address: https://github.com/marcusrognes/docs-smartlabs
git_edit_address: https://github.com/marcusrognes/docs-smartlabs/blob/gh-pages

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
